### ISSUE TITLE
JCABI heroku plugin documentation

### ISSUE THREAD

**Issue by NandishAndDev** [jcabi/jcabi#183]
jcabi heroku plugin documentation is very minimal. As a newbie to Heroku, the documentation is very small to appreciate its usefulness. Having used jcabi logging and jcabi cache I am sure this would also be great! Can documentation be extended with step by step procedure for a small app.

**Comment by dmarkov** [comment]
@yegor256 please don't close the issue, ask @NandishAndDev to do this instead, since he is the author of it

**Comment by yegor256** [comment]
@NandishAndDev please close this issue
