### ISSUE TITLE
Break entry and exit logs into two different lines

### ISSUE THREAD

**Issue by NandishAndDev** [jcabi/jcabi#184]
The entry and exit log statements for a function should be in two different lines. Why I would like this in this way is 
1. It will tell the exact flow
2. Traceability is enhanced

Current logging is also great , but from a profiling perspective. Shouldn't we have a option like
@Logging(formatStyle=Split) or @Logging(formatStyle=Single)

**Comment by dmarkov** [comment]
@yegor256 please don't close the issue, ask @NandishAndDev to do this instead, since he is the author of it

**Comment by yegor256** [comment]
@NandishAndDev please close this ticket
