### ISSUE TITLE
Using RetryOnFailure  annotation with Spring 3.0.5 does not work as expected

### ISSUE THREAD

**Issue by m-kumaran** [jcabi/jcabi#211]
Hi

I tried using RetryOnFailure annotation in a Spring application, but I could not make the method to retry when the exception is thrown from the method.
An example is pasted below.  Am I doing anything wrong here?

```
 import com.jcabi.aspects.RetryOnFailure;
 ... 
 ...
 @RetryOnFailure(attempts = 2)
public String testRetryOnFailure() throws NullPointerException{
    System.out.println("Method called:" + new Date());
    String ss =null;
    ss.trim(); // Expecting NullPointerException here..
    return null;
}
```

**Comment by mghose** [comment]
Hi, I cannot get retryOnFaillure to work. I am able to see a directory jcabi-ajc being created under the target , however when I try to run the method testRetry from main class , it does not get retried on failure.

This is the code I am using to test its usage  
public class MainTest {

    public static void main(String arg[])
            throws Exception {
        MainTest temp = new MainTest();
        temp.testRetry();
    }
    @RetryOnFailure ( attempts = 7)
    public String testRetry()
            throws NullPointerException {
        System.out.println("Method called:" + new Date());
        String ss =null;
        ss.trim(); // Expecting NullPointerException here..
        return null;

    }
}

Output:
Method called:Sun Mar 20 14:15:31 CDT 2016
Exception in thread "main" java.lang.NullPointerException
	at com.learn.corejava.MainTest.testRetry(MainTest.java:30)
	at com.learn.corejava.MainTest.main(MainTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

Process finished with exit code 1


PS:I have attached the pom file .

Appreciate any help!

[pom.txt](https://github.com/jcabi/jcabi/files/181481/pom.txt)
