### ISSUE TITLE
Allow @Loggable to accept a different logger than the one produced from LoggerFactory

### ISSUE THREAD

**Issue by fulgas** [jcabi/jcabi#247]
I have a logger being create at runtime and i would like to pass it to the Loggable annottation instead of getting a new one from the logger Factory.

Something like :

@Loggable(value = Loggable.DEBUG, skipArgs = true, skipResult = true, logger = this.logger)

**Comment by dmarkov** [comment]
@yegor256 only @fulgas can close this issue, since he opened it

**Comment by yegor256** [comment]
@fulgas please close this ticket
