### ISSUE TITLE
Aether dependency download is weird

### ISSUE THREAD

**Issue by Prevole** [jcabi/jcabi#253]
I encounter a strange behavior in my Maven Plugin code.

I am writing a plugin where I need to get a dependency and its children. 

My settings.xml contains a Mirrors sections with something like that:

``` xml
<mirrors>
  <mirror>
    <id>firstMirror</id>
    <url>http://releases</url>
    </mirrorOf>*,!secondMirror</mirrorOff>
  </mirror>
  <mirror>
    <id>secondMirror</id>
    <url>http://snapshots</url>
    </mirrorOf>*,!firstMirror</mirrorOff>
  </mirror>
</mirrors>
```

My code is the following:

``` java
public List<Artifact> getArtifacts(RepositorySystemSession repositorySystemSession, MavenProject project, String baseVersion) throws Exception {

  return new Aether(
    project,
    repositorySystemSession.getLocalRepository().getBasedir()).resolve(
    new DefaultArtifact("group-id", "artifact-id", "jar", baseVersion),
    JavaScopes.TEST
  );
}
```

When I run my maven plugin, I saw logs that try to download dependencies but in the wrong repository. Basically, the download is done from the SNAPSHOTS repository for dependencies that are not SNAPSHOTS.

I comment the Mirrors section, then the download is done from the Maven Central repository.

So I do not understand what is happening. Is it a bug or a wrong usage of the Aether lib ?

**Comment by dmarkov** [comment]
@yegor256 please don't close it.. @Prevole could you please close it, if it's done?
