### ISSUE TITLE
make servlet-api as optional dependency 

### ISSUE THREAD

**Issue by romani** [jcabi/jcabi#256]
From spec: http://www.jcabi.com/jcabi-manifests/
If you are outside of WAR application you should add Servlet API to compile-time classpath:
```
<dependency>
  <groupId>javax.servlet</groupId>
  <artifactId>servlet-api</artifactId>
  <version>2.4</version>
  <scope>provided</scope>
</dependency>
```

But it looks very weird to add to non service application servlet-api as dependency.
it would be nice to have it as optional.

Without that dependency you got "JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath"

Workaround is:
Another way to solve issue requeres chagnes in log4j.properties:
+log4j.logger.com.jcabi.aspects.aj.MethodValidator=FATAL

**Comment by dmarkov** [comment]
@yegor256 please don't close the issue, ask @romani to do this instead, since he is the author of it

**Comment by romani** [comment]
we already do not have that dependency and we use "0.7.12", we could close that issue.
