### ISSUE TITLE
JSR-303 error in jcabi-manifests on startup

### ISSUE THREAD

**Issue by lukelukeluke** [jcabi/jcabi#260]
Great utility, very useful!

When using jcabi-manifests with vanilla java (not EE) I end up with this error:

JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.

com.jcabi.aspects.aj.MethodValidator

...however, if I just ignore the error, Manifests.read still works fine.

**Comment by dmarkov** [comment]
@yegor256 only @lukelukeluke can close this issue, since he opened it

**Comment by yegor256** [comment]
@lukelukeluke please close this ticket

**Comment by essobedo** [comment]
@yegor256 

> It's a perfectly valid situation and doesn't harm your application at all

If so why it is an error then? A warning seems to be more appropriate in this case, don't you agree?

**Comment by yegor256** [comment]
@essobedo I agree, feel free to submit a ticket to jcabi-aspects project

**Comment by essobedo** [comment]
@yegor256 done https://github.com/jcabi/jcabi-aspects/issues/227

**Comment by yegor256** [comment]
@essobedo thanks
