### ISSUE TITLE
Qulice configuration - no license specified.

### ISSUE THREAD

**Issue by maurezen** [jcabi/jcabi#297]
1. Checkout master branch of any jcabi descendant
2. run `mvn qulice:check -Pqulice`
3. There are multiple `Line does not match expected header line of ' * BSD License'. (HeaderCheck)` messages.

This is a known bug of qulice configuration in parent-0.31 (jcabi/jcabi-parent#19). The fix has been [released](https://github.com/jcabi/jcabi-parent/pull/20#issuecomment-70816292) in parent-0.32.1. Please upgrade the version of parent to 0.32.1.

**Comment by dmarkov** [comment]
this task will get someone's attention soon

**Comment by dmarkov** [comment]
@maurezen thanks for the ticket, your account was topped for 15 mins, payment 50595982

**Comment by dmarkov** [comment]
@yegor256 it's your task now

**Comment by yegor256** [comment]
@rultor release, tag is `1.17`

**Comment by yegor256** [comment]
@maurezen version 1.17 was released to Maven Central, please review and close this ticket. thanks!

**Comment by maurezen** [comment]
@yegor256 thanks, closed.

**Comment by dmarkov** [comment]
@yegor256 **30 mins** was added to your account, many thanks for your contribution!... +30 to your rating, your total score is [+5940](http://www.netbout.com/b/35008?open=rating)
