### ISSUE TITLE
Upgrade to jcabi-parent 0.41

### ISSUE THREAD

**Issue by mkordas** [jcabi/jcabi#309]
Cosmetic: let's upgrade `jcabi-parent` to `0.41`. Main benefit would be the latest version of Qulice for jcabi projects.

**Comment by dmarkov** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@mkordas fixed in fdfea75

**Comment by yegor256** [comment]
@rultor release, tag is `1.22`
