### ISSUE TITLE
DomParser gives up before it tries parsing

### ISSUE THREAD

**Issue by jmd-usgs** [jcabi/jcabi#317]
I am getting java.lang.IllegalArgumentException: Doesn't look like XML: '[snip]...\OLD_001_QRev.xml'
	at com.jcabi.xml.DomParser.<init>(DomParser.java:90)
	at com.jcabi.xml.XMLDocument.<init>(XMLDocument.java:155) ...

I am using jcabi-xml-0.18.1.jar

The XML file parses fine elsewhere.  I believe DomParser is giving up before it actually tries to parse the file.

Right now, I think the DomParser code is doing something like:

    if (pattern doesn't match) {
        throw "Doesn't look like XML"
    }
    parse()

Could it be changed to something like:
    
    try {
        parse()
    } catch (Exception e) {
        if (pattern doesn't match) {
            throw "Doesn't look like XML"
        } else {
            rethrow e
        }
    }

I can provide the XML file, if needed.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@jmd-usgs can you please post this issue to this project: https://github.com/jcabi/jcabi-xml Together with your XML and the Java code. Thanks!
