### ISSUE TITLE
Not working with MySQL driver

### ISSUE THREAD

**Issue by NyxMC** [jcabi/jcabi#318]
`val id = JdbcSession(source)`
`           .sql("INSERT INTO Test (data) VALUES (?);")`
`           .set("MyData")`
`           .insert(Outcome.LAST_INSERT_ID)`
This produces the following exception: [stacktrace](https://hastebin.com/hidabidupe.pl)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by NyxMC** [comment]
wow. now I'm confused. [This code](https://hastebin.com/obapubifuk.kotlin) results in [this exception](https://hastebin.com/ziseheruwu.sql). Really strange.

**Comment by NyxMC** [comment]
Now I'm confused! [This code](https://hastebin.com/miyemobuja.kotlin) results in [this exception](https://hastebin.com/jipolamepe.sql). Strange.

**Comment by yegor256** [comment]
@NyxMC can you please re-submit this issue to [jcabi/jcabi-jdbc](https://github.com/jcabi/jcabi-jdbc)

**Comment by 0crat** [comment]
@yegor256 please, ask @nyxmc to close this issue and [read more](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue
