### ISSUE TITLE
jcabi-jdbc requires aspectj

### ISSUE THREAD

**Issue by nshusa** [jcabi/jcabi#320]
For my mysql project I can't use jcabi-jdbc as it requires aspectj. For my postgres project I don't get this issue? Why am I getting this? I added jcabi-jdbc-0.16 to my classpath.

![IMAGE](https://i.imgur.com/ce7xY5d.png)

![IMAGE](https://i.imgur.com/TMkncXW.png)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@nshusa can you please submit this ticket here: https://github.com/jcabi/jcabi-jdbc Thanks.
