### ISSUE TITLE
Update to latest jcabi-parent

### ISSUE THREAD

**Issue by andreoss** [jcabi/jcabi#325]
Latest jcabi-parent elevate dependencies for JDK 11 builds

And fixes issues like
https://github.com/rzwitserloot/lombok/issues/1572 (https://github.com/jcabi/jcabi-parent/blob/0.50.3/pom.xml#L1421)
https://github.com/jcabi/jcabi-matchers/pull/44

**Comment by yegor256** [comment]
@rultor release, tag is `1.26.0`
