### ISSUE TITLE
Why jcabi-maven-slf4j needs sisu-inject-plexus as runtime dependency?

### ISSUE THREAD

**Issue by tsachev** [jcabi/jcabi#50]
Hi,
I need to write a maven plugin which integrates a code generator component to our maven build. This component uses slf4j for logging and I found that slf4j to maven log binding.
It works as expected, but I was wondering why it needs sisu-inject-plexus as runtime dependency?
After excluding it it still works as expected.

**Comment by dmarkov** [comment]
@yegor256 only @tsachev can close this issue, since he opened it

**Comment by yegor256** [comment]
@tsachev please close this issue
